spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee_db
    password: admin
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

springs:
  boot:
    message: Hello Employee Service Updated Spring cloud bus demo
